spring.profiles.active=test
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/pensionat_db_test
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME:root}
customer-service.base-url=http://localhost:8081
reviews-service.base-url=http://localhost:8082